name: webriffs_client
version: 0.1.0
author: Groboclown <matt@groboclown.net>
environment:
  sdk: '>=1.6.0'
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: any
  cookie: '>=0.0.4 <1.0.0'
  videoplay: '>=0.2.4 <1.0.0'
  web_components: any
dev_dependencies:
  unittest: any
  template_cache_transformer: any
transformers:
  - angular:
      html_files: "web/main.html"
      $exclude: [ "web/index.html" ]
  - $dart2js:
      # Testing should always enable this.
      #checked: true
      checked: false
      minify: true
      #dumpInfo: true
      commandLineOptions: [ "--dump-info" ]
      $exclude: [ "web/index.html" ]
  #- template_cache_transformer:
  #    entry_point: webriffs_client|web/main.html
  #    $exclude: [ "web/index.html" ]
